blank_issues_enabled: false
contact_links:
  - name: Gitter Community Forum
    url: https://gitter.im/erikras/redux-form
    about: Please ask and answer questions here.
  - name: StackOverflow
    url: https://stackoverflow.com/questions/tagged/redux-form
    about: Please ask and answer questions here.
  - name: Spectrum Community Forum
    url: https://spectrum.chat/redux-form
    about: Please ask and answer questions here.
